class MergedIndex:
    def add(self, chunks: list[dict]) -> None: ...
    def search(self, query: str, k: int) -> list[tuple[float, dict]]: ...

class PerDocIndexes:
    def add(self, doc_id: str, chunks: list[dict]) -> None: ...
    def search_all(self, query: str, k_per_doc: int) -> dict[str, list[tuple[float,dict]]]: ...
